// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/12/2024, 10:40:49 PM
const configMerger = require("/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.0_rollup@4.12.1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/plugins/**/*.{js,ts,mjs}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/utils/**/**/*.{js,ts,mjs}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/composables/**/*.{js,ts,mjs}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/utils/**/*.{js,ts,mjs}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/roccopunghellini/Sites/beatricegaspari.com/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
