// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_sanity/fetch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sanity@1.11.3_rollup@4.12.1/node_modules/@nuxtjs/sanity/dist/runtime/server/routes/proxy').default>>>>
    }
    '/preview/enable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sanity@1.11.3_rollup@4.12.1/node_modules/@nuxtjs/sanity/dist/runtime/server/routes/preview/enable').default>>>>
    }
    '/preview/disable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sanity@1.11.3_rollup@4.12.1/node_modules/@nuxtjs/sanity/dist/runtime/server/routes/preview/disable').default>>>>
    }
  }
}
export {}