// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.8_nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_r_llizfb6su7cd3qg6el3ncieql4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.8_nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_r_llizfb6su7cd3qg6el3ncieql4/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+sanity@1.11.3_rollup@4.12.1/node_modules/@nuxtjs/sanity/dist/runtime/plugins/visual-editing.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+sanity@1.11.3_rollup@4.12.1/node_modules/@nuxtjs/sanity/dist/runtime/plugins/visual-editing.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.10.3_@parcel+watcher@2.4.1_@types+node@20.11.25_encoding@0.1.13_rollup@4.12.1_terser@5_6mds264eqtls6pjmy6jomnvjly/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default> &
  InjectionType<typeof import("../../plugins/mq").default> &
  InjectionType<typeof import("../../plugins/ratio").default> &
  InjectionType<typeof import("../../plugins/viewport").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'viewport' | 'nuxt:revive-payload:server' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:chunk-reload' | 'nuxt:checkIfLayoutUsed' | 'ratio'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
